<?php

declare(strict_types=1);

namespace Pig\Ai\Antigravity;

use Pig\Ai\ProviderError;

/**
 * Which model Antigravity is actually asked for, and by what name.
 *
 * **The ids people choose from are not the ids that go out.** `gemini-3.8-flash` is a *logical*
 * model; the thinking level picks a **runtime** id from it (`gemini-3.8-flash-medium`), and that
 * is sent as an **enum** (`MODEL_PLACEHOLDER_M319`). Three names for one choice, and a request
 * carrying the wrong one of the three is rejected rather than misrouted.
 *
 * Nothing in the rest of pig works this way: a `Model` has one id, and `ThinkingLevel` maps to a
 * reasoning effort rather than to another model. So this lives inside the provider — the registry
 * keeps offering one id per model, and the translation happens where the request is built. That
 * is also why it is here and not on `Model`: no other provider has an opinion about it.
 *
 * **The tables are generated, not transcribed.** `scripts/fetch-antigravity-models.php` prints
 * them from the deployment's own catalogue, which is the only authority there is — models.dev
 * does not carry a subscription deployment's catalogue and upstream deleted its Antigravity
 * support altogether. See the CLAUDE.md entry.
 *
 * Only the runtime ids reachable through routing are kept. The catalogue also enumerates the
 * Antigravity IDE's own models — tab completion, its chat surfaces, image generation, the
 * `-tiered` variants — and a table listing models nothing here can ask for is a table that
 * invites somebody to ask for them.
 */
final class Routing
{
    /**
     * logical id => the runtime id each thinking level asks for.
     *
     * `off` is **absent** for a model that cannot have thinking turned off, rather than present
     * and empty. `claude-opus-4-6` and `gpt-oss-120b` are the two, and the catalogue agrees with
     * itself about it: their `thinkingLevelMap` says `off: null` for the same reason.
     *
     * @var array<string, array{default: string, off?: string, levels: array<string, string>}>
     */
    private const array ROUTING = [
        // >>> generated by scripts/fetch-antigravity-models.php
        'claude-opus-4-6' => ['default' => 'claude-opus-4-6-thinking', 'levels' => ['high' => 'claude-opus-4-6-thinking', 'low' => 'claude-opus-4-6-thinking', 'medium' => 'claude-opus-4-6-thinking', 'minimal' => 'claude-opus-4-6-thinking']],
        'claude-sonnet-4-6' => ['default' => 'claude-sonnet-4-6', 'off' => 'claude-sonnet-4-6', 'levels' => ['high' => 'claude-sonnet-4-6', 'low' => 'claude-sonnet-4-6', 'medium' => 'claude-sonnet-4-6', 'minimal' => 'claude-sonnet-4-6', 'xhigh' => 'claude-sonnet-4-6']],
        'gemini-2.5-flash' => ['default' => 'gemini-2.5-flash-thinking', 'off' => 'gemini-2.5-flash-thinking', 'levels' => ['high' => 'gemini-2.5-flash-thinking', 'low' => 'gemini-2.5-flash-thinking', 'medium' => 'gemini-2.5-flash-thinking', 'minimal' => 'gemini-2.5-flash-thinking', 'xhigh' => 'gemini-2.5-flash-thinking']],
        'gemini-2.5-flash-lite' => ['default' => 'gemini-2.5-flash-lite', 'off' => 'gemini-2.5-flash-lite', 'levels' => ['high' => 'gemini-2.5-flash-lite', 'low' => 'gemini-2.5-flash-lite', 'medium' => 'gemini-2.5-flash-lite', 'minimal' => 'gemini-2.5-flash-lite', 'xhigh' => 'gemini-2.5-flash-lite']],
        'gemini-2.5-pro' => ['default' => 'gemini-2.5-pro', 'off' => 'gemini-2.5-pro', 'levels' => ['high' => 'gemini-2.5-pro', 'low' => 'gemini-2.5-pro', 'medium' => 'gemini-2.5-pro', 'minimal' => 'gemini-2.5-pro', 'xhigh' => 'gemini-2.5-pro']],
        'gemini-3-flash' => ['default' => 'gemini-3-flash', 'off' => 'gemini-3-flash', 'levels' => ['high' => 'gemini-3-flash', 'low' => 'gemini-3-flash', 'medium' => 'gemini-3-flash', 'minimal' => 'gemini-3-flash', 'xhigh' => 'gemini-3-flash']],
        'gemini-3.1-flash-lite' => ['default' => 'gemini-3.1-flash-lite', 'off' => 'gemini-3.1-flash-lite', 'levels' => ['high' => 'gemini-3.1-flash-lite', 'low' => 'gemini-3.1-flash-lite', 'medium' => 'gemini-3.1-flash-lite', 'minimal' => 'gemini-3.1-flash-lite', 'xhigh' => 'gemini-3.1-flash-lite']],
        'gemini-3.1-pro' => ['default' => 'gemini-3.1-pro-low', 'off' => 'gemini-3.1-pro-low', 'levels' => ['high' => 'gemini-pro-agent', 'low' => 'gemini-3.1-pro-low', 'medium' => 'gemini-3.1-pro-low', 'minimal' => 'gemini-3.1-pro-low', 'xhigh' => 'gemini-pro-agent']],
        'gemini-3.5-flash' => ['default' => 'gemini-3.5-flash-extra-low', 'off' => 'gemini-3.5-flash-extra-low', 'levels' => ['high' => 'gemini-3-flash-agent', 'low' => 'gemini-3.5-flash-extra-low', 'medium' => 'gemini-3.5-flash-low', 'minimal' => 'gemini-3.5-flash-extra-low', 'xhigh' => 'gemini-3-flash-agent']],
        'gemini-3.5-flash-lite' => ['default' => 'gemini-3.5-flash-lite', 'off' => 'gemini-3.5-flash-lite', 'levels' => ['high' => 'gemini-3.5-flash-lite', 'low' => 'gemini-3.5-flash-lite', 'medium' => 'gemini-3.5-flash-lite', 'minimal' => 'gemini-3.5-flash-lite', 'xhigh' => 'gemini-3.5-flash-lite']],
        'gemini-3.6-flash' => ['default' => 'gemini-3.6-flash-low', 'off' => 'gemini-3.6-flash-low', 'levels' => ['high' => 'gemini-3.6-flash-high', 'low' => 'gemini-3.6-flash-low', 'medium' => 'gemini-3.6-flash-medium', 'minimal' => 'gemini-3.6-flash-low', 'xhigh' => 'gemini-3.6-flash-high']],
        'gemini-3.7-flash' => ['default' => 'gemini-3.7-flash-low', 'off' => 'gemini-3.7-flash-low', 'levels' => ['high' => 'gemini-3.7-flash-high', 'low' => 'gemini-3.7-flash-low', 'medium' => 'gemini-3.7-flash-medium', 'minimal' => 'gemini-3.7-flash-low', 'xhigh' => 'gemini-3.7-flash-high']],
        'gemini-3.8-flash' => ['default' => 'gemini-3.8-flash-low', 'off' => 'gemini-3.8-flash-low', 'levels' => ['high' => 'gemini-3.8-flash-high', 'low' => 'gemini-3.8-flash-low', 'medium' => 'gemini-3.8-flash-medium', 'minimal' => 'gemini-3.8-flash-low', 'xhigh' => 'gemini-3.8-flash-high']],
        'gpt-oss-120b' => ['default' => 'gpt-oss-120b-medium', 'off' => 'gpt-oss-120b-medium', 'levels' => ['high' => 'gpt-oss-120b-medium', 'low' => 'gpt-oss-120b-medium', 'medium' => 'gpt-oss-120b-medium', 'minimal' => 'gpt-oss-120b-medium']],
        // <<< generated
    ];

    /**
     * runtime id => what the wire calls it.
     *
     * @var array<string, string>
     */
    private const array ENUMS = [
        // >>> generated by scripts/fetch-antigravity-models.php
        'claude-opus-4-6-thinking' => 'MODEL_PLACEHOLDER_M26',
        'claude-sonnet-4-6' => 'MODEL_PLACEHOLDER_M35',
        'gemini-2.5-flash-lite' => 'MODEL_GOOGLE_GEMINI_2_5_FLASH_LITE',
        'gemini-2.5-flash-thinking' => 'MODEL_GOOGLE_GEMINI_2_5_FLASH_THINKING',
        'gemini-2.5-pro' => 'MODEL_GOOGLE_GEMINI_2_5_PRO',
        'gemini-3-flash' => 'MODEL_PLACEHOLDER_M18',
        'gemini-3-flash-agent' => 'MODEL_PLACEHOLDER_M84',
        'gemini-3.1-flash-lite' => 'MODEL_PLACEHOLDER_M50',
        'gemini-3.1-pro-low' => 'MODEL_PLACEHOLDER_M36',
        'gemini-3.5-flash-extra-low' => 'MODEL_PLACEHOLDER_M187',
        'gemini-3.5-flash-lite' => 'MODEL_PLACEHOLDER_M198',
        'gemini-3.5-flash-low' => 'MODEL_PLACEHOLDER_M20',
        'gemini-3.6-flash-high' => 'MODEL_PLACEHOLDER_M71',
        'gemini-3.6-flash-low' => 'MODEL_PLACEHOLDER_M73',
        'gemini-3.6-flash-medium' => 'MODEL_PLACEHOLDER_M72',
        'gemini-3.7-flash-high' => 'MODEL_PLACEHOLDER_M298',
        'gemini-3.7-flash-low' => 'MODEL_PLACEHOLDER_M300',
        'gemini-3.7-flash-medium' => 'MODEL_PLACEHOLDER_M299',
        'gemini-3.8-flash-high' => 'MODEL_PLACEHOLDER_M318',
        'gemini-3.8-flash-low' => 'MODEL_PLACEHOLDER_M320',
        'gemini-3.8-flash-medium' => 'MODEL_PLACEHOLDER_M319',
        'gemini-pro-agent' => 'MODEL_PLACEHOLDER_M16',
        'gpt-oss-120b-medium' => 'MODEL_OPENAI_GPT_OSS_120B_MEDIUM',
        // <<< generated
    ];

    /** Every logical model this provider can be asked for. */
    public static function models(): array
    {
        return array_keys(self::ROUTING);
    }

    public static function knows(string $model): bool
    {
        return isset(self::ROUTING[$model]);
    }

    /**
     * What to send for $model at $level: the runtime id and the enum it goes out as.
     *
     * $level is `ThinkingLevel`'s value, or null for a turn with thinking off.
     *
     * **An unknown model is an error, not a default.** The implementation this was ported from
     * ends its lookup chain with "otherwise Gemini 3.8 Flash", which is the right answer for a
     * gateway taking whatever a client sends and the wrong one here: pig's registry is built from
     * these very tables, so an id that misses can only be a bug in pig — and answering it with a
     * different model than the one on screen is the kind of bug that never gets found. Same for a
     * runtime id with no enum, which means the tables were regenerated inconsistently.
     *
     * @return array{string, string} the runtime id, and its enum
     */
    public static function resolve(string $model, ?string $level): array
    {
        $entry = self::ROUTING[$model]
            ?? throw new ProviderError("Antigravity has no model '{$model}'. Regenerate the routing tables with scripts/fetch-antigravity-models.php.");

        // `off` when there is one, the default when the model cannot be turned off. Reaching the
        // second is already unusual — `ThinkingLevel::supportedBy()` keeps `off` out of the
        // picker for those models — so this is the floor under that rather than a path in use.
        $runtime = $level === null || $level === 'off'
            ? ($entry['off'] ?? $entry['default'])
            : ($entry['levels'][$level] ?? $entry['default']);

        $enum = self::ENUMS[$runtime]
            ?? throw new ProviderError("Antigravity runtime model '{$runtime}' has no enum. The routing and enum tables disagree; regenerate both.");

        return [$runtime, $enum];
    }

    /**
     * How many tokens of thinking to ask for, by runtime id and level.
     *
     * **Hand-tuned and not from the catalogue**, which carries no budgets — ported as-is from a
     * working implementation, including the numbers that look arbitrary. `10001` and `1001` for
     * the Pro models are one more than the Flash figures and that is in the original too; a
     * rounder number here is a change to what the models are asked for, not a tidy-up.
     *
     * `-1` is Antigravity's "as much as you like" for Gemini at the top levels.
     */
    public static function thinkingBudget(string $runtime, ?string $level): int
    {
        if ($level === null || $level === 'off') {
            return 0;
        }

        if (str_starts_with($runtime, 'claude-')) {
            return 1024;
        }

        if (str_starts_with($runtime, 'gpt-oss-')) {
            return 8192;
        }

        if (str_starts_with($runtime, 'gemini-3.5-flash') || $runtime === 'gemini-3-flash-agent') {
            return match ($level) {
                'high', 'xhigh' => 10_000,
                'medium' => 4_000,
                default => 1_000,
            };
        }

        if (str_starts_with($runtime, 'gemini-3.1-pro') || $runtime === 'gemini-pro-agent') {
            return match ($level) {
                'high', 'xhigh' => 10_001,
                default => 1_001,
            };
        }

        if (str_starts_with($runtime, 'gemini-')) {
            return match ($level) {
                'high', 'xhigh' => -1,
                'medium' => 4_000,
                default => 1_000,
            };
        }

        return 0;
    }
}
