#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Rewrite `Ai\Models`' tables from models.dev.
 *
 * `php scripts/generate-models.php [--from <file>] [--dry-run]`
 *
 * **Why this exists, which is the whole argument for it.** `Ai\Models` was a transcription: 178
 * rows copied by hand out of upstream's `models.generated.ts` at the anchor commit, and
 * `CLAUDE.md` called the freeze fidelity — *"the figures are upstream's at the anchor commit,
 * which is the source a port should agree with rather than whatever models.dev says today"*. That
 * is fidelity to the bytes and not to the mechanism. **Upstream has never kept this table by
 * hand**: the file pig copied from opens with
 *
 *     // This file is auto-generated by scripts/generate-models.ts
 *     // Do not edit manually - run 'npm run generate-models' to update
 *
 * and by upstream HEAD the data is not in git at all — each provider's catalogue is fetched from
 * models.dev at build time. So pig froze the *output* of a generator and then treated the freeze
 * as a decision. The price came due twice: Groq answered `404 … does not exist` for
 * `llama-3.3-70b-versatile`, a row `--list-models` still offered, and `gemini-3.8-flash` — a real
 * model — had to be hand-declared in `models.json` to be reachable at all.
 *
 * **Porting the anchor forward would not have fixed either**, because upstream HEAD has no table
 * to port. This is the thing that fixes it, and it leaves the port anchor exactly where it was:
 * `d0a4c37` still decides every line of *protocol*, and the registry stops being protocol and
 * goes back to being what it always was, a directory of what providers currently sell.
 *
 * What it does **not** do, on purpose:
 *
 * - **It writes rows, not files.** Each table in `Models.php` carries a `>>> generated` /
 *   `<<< generated` pair and only what lies between them is replaced, so every docblock, base
 *   URL, `RESOLD` entry and Copilot header stays hand-written and a regeneration's diff is the
 *   rows and nothing else.
 * - **It does not touch `ANTIGRAVITY_MODELS`.** That one is hand-written in
 *   *upstream's* generator too — models.dev does not carry a subscription deployment's catalogue —
 *   so they are hand-written here for the same reason and not for want of trying.
 * - **It does not add providers.** The filter is "the protocol is ported", which is `Models`' own
 *   standing rule: offering a model and then failing to send the request is a worse answer than
 *   "no such model". DeepSeek is the one worth naming — upstream ships it at HEAD, pig has no
 *   entry, and adding one is a decision about `OpenAiCompat` rather than a row in a table.
 * - **It never writes silently.** Every run prints what changed against the table that was
 *   loaded before the rewrite: added, gone, and every field that moved. A regeneration nobody
 *   read is a registry nobody checked.
 *
 * `--from` reads a saved `api.json` instead of fetching. Not a seam for a test: models.dev is
 * unreachable from some of the machines this repository is worked on, a regeneration from the
 * snapshot somebody else fetched is the only way to reproduce a table, and a generator whose
 * input cannot be pinned is a generator whose output cannot be explained.
 *
 * `--dry-run` writes nothing and prints the rows it would have written, which is the shape worth
 * reading before overwriting a table and is also the only way the rendering is checkable without
 * a file on disk to compare against.
 */

$autoload = is_file(__DIR__ . '/../vendor/autoload.php')
    ? __DIR__ . '/../vendor/autoload.php'
    : __DIR__ . '/../../../autoload.php';

if (!is_file($autoload)) {
    fwrite(STDERR, "Error: Could not locate Composer autoloader.\n");
    exit(1);
}

require $autoload;

use Pig\Ai\Api;
use Pig\Ai\Http\HttpClient;
use Pig\Ai\Http\Request;
use Pig\Ai\Model;
use Pig\Ai\Models;
use Pig\Async\Async;

const MODELS_DEV = 'https://models.dev/api.json';

const TABLE = __DIR__ . '/../packages/ai/src/Models.php';

/**
 * provider on models.dev => [pig's constant, the api, the base URL]
 *
 * The three columns upstream's script varies per provider and nothing else does. `github-copilot`
 * is absent because its api is per model — see `copilotApi()`. `amazon-bedrock`'s base URL is per
 * model too (upstream's `getBedrockBaseUrl()`, which `Models` applies to each row): the one named
 * here is everything but the `eu.` inference profiles'.
 *
 * @var array<string, array{0: string, 1: Api, 2: string}>
 */
const DIRECT = [
    'anthropic' => ['ANTHROPIC_MODELS', Api::AnthropicMessages, 'https://api.anthropic.com'],
    'openai' => ['OPENAI_MODELS', Api::OpenAiResponses, 'https://api.openai.com/v1'],
    'google' => ['GOOGLE_MODELS', Api::GoogleGenerativeAi, 'https://generativelanguage.googleapis.com/v1beta'],
    'google-vertex' => ['GOOGLE_VERTEX_MODELS', Api::GoogleVertex, 'https://{location}-aiplatform.googleapis.com'],
    'cerebras' => ['CEREBRAS_MODELS', Api::OpenAiCompletions, 'https://api.cerebras.ai/v1'],
    'groq' => ['GROQ_MODELS', Api::OpenAiCompletions, 'https://api.groq.com/openai/v1'],
    'mistral' => ['MISTRAL_MODELS', Api::MistralConversations, 'https://api.mistral.ai'],
    'xai' => ['XAI_MODELS', Api::OpenAiCompletions, 'https://api.x.ai/v1'],
    'zai' => ['ZAI_MODELS', Api::OpenAiCompletions, 'https://api.z.ai/api/coding/paas/v4'],
    'amazon-bedrock' => ['AMAZON_BEDROCK_MODELS', Api::BedrockConverseStream, 'https://bedrock-runtime.us-east-1.amazonaws.com'],
];

/**
 * provider => the models.dev entry its rows are read from, where that is not the provider's own name.
 *
 * Upstream's `processZaiModels()`: pig's `zai` is z.ai's **coding plan** endpoint
 * (`api.z.ai/api/coding/paas/v4`), and models.dev lists that plan's models under
 * `zai-coding-plan`, not under `zai` — whose list is the pay-as-you-go API's, with models the
 * coding plan does not serve. The prices are still read from `zai` when it lists the model
 * (`data.zai?.models[modelId]?.cost ?? m.cost`), the plan's own entry being the fallback.
 */
const SOURCE = [
    'zai' => 'zai-coding-plan',
];

/**
 * Upstream's `isGlm52` in `processZaiModels()`: the two GLM-5.2 ids whose effort map, when they
 * have one, says `off: "none"`. (`ZAI_TOOL_STREAM_UNSUPPORTED_MODELS`, the other z.ai list, is read
 * at run time by `Models`, which is where pig works out a built-in model's compat.)
 */
const ZAI_GLM52_IDS = ['glm-5.2', 'glm-5.2-highspeed'];

/**
 * Upstream's `GITHUB_COPILOT_EXTENDED_CONTEXT_MODELS`: "GitHub's 'Models with extended capabilities'
 * table lists these Copilot models as supporting the extended 1 million token context window."
 * Applied by `copilotTemporaryOverrides()` to every Copilot row whose id is listed, whatever the
 * catalogue said — 200,000 for some, 400,000 for one, 1,050,000 for others.
 */
const GITHUB_COPILOT_EXTENDED_CONTEXT_MODELS = [
    'claude-fable-5',
    'claude-opus-4.6',
    'claude-opus-4.7',
    'claude-opus-4.8',
    'claude-opus-5',
    'claude-opus-5.5',
    'claude-sonnet-4.6',
    'claude-sonnet-5',
    'gpt-5.3-codex',
    'gpt-5.4',
    'gpt-5.5',
    'gpt-6-astra',
    'gpt-6-luna',
    'gpt-6-sol',
];

/**
 * Upstream's `OPENAI_LONG_CONTEXT_INPUT_THRESHOLD`: OpenAI bills a request over 272k input tokens at
 * the long-context rates, and the capped models' window stops there.
 */
const OPENAI_LONG_CONTEXT_INPUT_THRESHOLD = 272_000;

/**
 * Upstream's `OPENAI_SHORT_CONTEXT_CAPPED_MODEL_IDS`: "Keep direct OpenAI requests in the
 * short-context pricing tier by default. Users can opt into the larger context through model
 * overrides, so retain long-context cost metadata on the capped models." The window is what
 * compaction fires against, so these compact before a request reaches the dearer tier.
 */
const OPENAI_SHORT_CONTEXT_CAPPED_MODEL_IDS = [
    'gpt-5.4',
    'gpt-5.5',
    'gpt-5.6-sol',
    'gpt-5.6-terra',
    'gpt-5.6-luna',
    'gpt-6-astra',
    'gpt-6-sol',
    'gpt-6-luna',
    'gpt-6.1-sol',
];

/** Upstream's `OPENAI_LONG_CONTEXT_PRICING_MODEL_IDS`: the `openai` rows that get the 272k tier. */
const OPENAI_LONG_CONTEXT_PRICING_MODEL_IDS = [
    'gpt-5.4',
    'gpt-5.4-pro',
    'gpt-5.5',
    'gpt-5.5-pro',
    'gpt-5.6-sol',
    'gpt-5.6-terra',
    'gpt-5.6-luna',
    'gpt-6-astra',
    'gpt-6-sol',
    'gpt-6-luna',
    'gpt-6.1-sol',
];

/**
 * Upstream's `OPENAI_STANDARD_COSTS`, in a row's price keys: "Keep current OpenAI prices
 * authoritative until models.dev and passthrough catalogs catch up."
 * https://developers.openai.com/api/docs/pricing
 *
 * @var array<string, array{input: float, out: float, cacheRead: float, cacheWrite: float}>
 */
const OPENAI_STANDARD_COSTS = [
    'gpt-5.6-luna' => ['input' => 0.2, 'out' => 1.2, 'cacheRead' => 0.02, 'cacheWrite' => 0.25],
    'gpt-5.6-sol' => ['input' => 4.0, 'out' => 20.0, 'cacheRead' => 0.4, 'cacheWrite' => 5.0],
    'gpt-5.6-terra' => ['input' => 2.0, 'out' => 12.0, 'cacheRead' => 0.2, 'cacheWrite' => 2.5],
    'gpt-6-astra' => ['input' => 10.0, 'out' => 50.0, 'cacheRead' => 1.0, 'cacheWrite' => 12.5],
    'gpt-6-luna' => ['input' => 0.1, 'out' => 0.5, 'cacheRead' => 0.01, 'cacheWrite' => 0.125],
    'gpt-6-sol' => ['input' => 2.0, 'out' => 10.0, 'cacheRead' => 0.2, 'cacheWrite' => 2.5],
    'gpt-6.1-sol' => ['input' => 2.0, 'out' => 10.0, 'cacheRead' => 0.1, 'cacheWrite' => 2.5],
];

/**
 * The providers whose models.dev `reasoning_options` upstream records
 * (`recordModelsDevReasoningOptions()`) for `applyModelsDevReasoningOptionMetadata()`, among the
 * ones pig generates. Google and Mistral are not here because upstream does not record theirs:
 * their rows take a `thinkingLevelMap` where they are built — `getGoogleThinkingLevelMap()` and
 * `getEffortThinkingLevelMap()` — which `rowsFor()` writes as the row's own `thinkingLevelMap`. z.ai
 * is here *and* gets a built map, as upstream's `processZaiModels()` does both; its recorded options
 * never apply, because `thinkingFormat: "zai"` fails `supportsDirectReasoningEffort()`.
 */
const REASONING_OPTION_PROVIDERS = ['anthropic', 'openai', 'cerebras', 'groq', 'xai', 'zai', 'github-copilot'];

/** Upstream's `THINKING_LEVELS` in `models-dev-reasoning-options.ts` — no `off`, which `none` stands for. */
const EFFORT_THINKING_LEVELS = ['minimal', 'low', 'medium', 'high', 'xhigh', 'max'];

/**
 * What models.dev gets wrong, and what it does not carry yet.
 *
 * Upstream's own corrections, ported with their reasons rather than their values alone, because a
 * number with no reason beside it is a number nobody can ever retire. Each is keyed
 * `provider/id`; each `add` supplies a row models.dev does not carry yet, and is dropped once it does.
 *
 * **Corrections used to live here too, and were retired.** Copilot's extended windows are a rule
 * now, like upstream's (`GITHUB_COPILOT_EXTENDED_CONTEXT_MODELS`, `copilotTemporaryOverrides()`);
 * Opus 4.5's cache pricing and the five Gemini 3.x refused-level measurements were retired when
 * models.dev started saying the same thing.
 *
 * @var array<string, array{kind: string, why: string, row: array<string, mixed>}>
 */
const OVERRIDES = [
    // Upstream's `missingCopilotModels`: "The authenticated Copilot catalog advertised these models
    // on 2026-09-22, but models.dev did not include them yet." Added only when the catalogue lacks
    // them, as upstream's `!allModels.some(...)` does. Copilot's GPT-6 rows are priced
    // `withOpenAiLongContextPricing(OPENAI_STANDARD_COSTS[id])`, written out here.
    'github-copilot/claude-opus-5.5' => [
        'kind' => 'add',
        'why' => 'upstream adds it until models.dev lists it',
        'row' => [
            'name' => 'Claude Opus 5.5', 'reasoning' => true, 'images' => true,
            'context' => 1_000_000, 'output' => 128_000,
            'input' => 4.0, 'out' => 20.0, 'cacheRead' => 0.2, 'cacheWrite' => 5.0,
            'thinkingLevelMap' => ['off' => null, 'minimal' => null, 'low' => 'low', 'medium' => 'medium', 'high' => 'high', 'xhigh' => 'xhigh', 'max' => 'max'],
        ],
    ],
    'github-copilot/gpt-6-sol' => [
        'kind' => 'add',
        'why' => 'upstream adds it until models.dev lists it',
        'row' => [
            'name' => 'GPT-6 Sol', 'reasoning' => true, 'images' => true, 'context' => 1_000_000, 'output' => 128_000,
            ...OPENAI_STANDARD_COSTS['gpt-6-sol'], 'tiers' => [[272_000, 4.0, 15.0, 0.4, 5.0]],
        ],
    ],
    'github-copilot/gpt-6-luna' => [
        'kind' => 'add',
        'why' => 'upstream adds it until models.dev lists it',
        'row' => [
            'name' => 'GPT-6 Luna', 'reasoning' => true, 'images' => true, 'context' => 1_000_000, 'output' => 128_000,
            ...OPENAI_STANDARD_COSTS['gpt-6-luna'], 'tiers' => [[272_000, 0.2, 0.75, 0.02, 0.25]],
        ],
    ],
    // Upstream: "Add missing Mistral Medium 3.5 model until models.dev includes it", with
    // `getEffortThinkingLevelMap([{type: "effort", values: ["none", "high"]}])` and a 256k window.
    'mistral/mistral-medium-3.5' => [
        'kind' => 'add',
        'why' => 'upstream adds it until models.dev lists it',
        'row' => [
            'name' => 'Mistral Medium 3.5', 'reasoning' => true, 'images' => true,
            'context' => 262_144, 'output' => 262_144,
            'input' => 1.5, 'out' => 7.5, 'cacheRead' => 0.0, 'cacheWrite' => 0.0,
            'thinkingLevelMap' => ['off' => 'none', 'minimal' => null, 'low' => null, 'medium' => null, 'high' => 'high', 'xhigh' => null, 'max' => null],
        ],
    ],
    // Upstream's own hand-added row: "Add Claude Haiku 5.5 until models.dev includes it. Prompts
    // over 100k input tokens are billed at 5x for the whole request."
    // https://platform.claude.com/docs/en/models/haiku-5-5/overview
    'anthropic/claude-haiku-5-5' => [
        'kind' => 'add',
        'why' => 'models.dev does not list it yet',
        'row' => [
            'name' => 'Claude Haiku 5.5', 'reasoning' => true, 'images' => true,
            'context' => 1_000_000, 'output' => 128_000,
            'input' => 0.1, 'out' => 0.5, 'cacheRead' => 0.01, 'cacheWrite' => 0.125,
            'tiers' => [[100_000, 0.5, 2.5, 0.05, 0.625]],
        ],
    ],
    'openai/gpt-5-chat-latest' => [
        'kind' => 'add',
        'why' => 'models.dev does not list it',
        'row' => [
            'name' => 'GPT-5 Chat Latest', 'reasoning' => false, 'images' => true,
            'context' => 128_000, 'output' => 16_384,
            'input' => 1.25, 'out' => 10.0, 'cacheRead' => 0.125, 'cacheWrite' => 0.0,
        ],
    ],
    // Upstream's `missingOpenAiModels` ("Add missing gpt models"): each at the 272k window and
    // `OPENAI_STANDARD_COSTS`, added only when the catalogue lacks it. The long-context tier is not
    // written here because `openAiTemporaryOverrides()` puts it on every one of these ids anyway —
    // upstream's rows carry `withOpenAiLongContextPricing(OPENAI_STANDARD_COSTS[id])`, the same value.
    'openai/gpt-6.1-sol' => [
        'kind' => 'add',
        'why' => 'upstream adds it until models.dev lists it',
        'row' => ['name' => 'GPT-6.1 Sol', 'reasoning' => true, 'images' => true, 'context' => 272_000, 'output' => 128_000, ...OPENAI_STANDARD_COSTS['gpt-6.1-sol']],
    ],
    'openai/gpt-6-astra' => [
        'kind' => 'add',
        'why' => 'upstream adds it until models.dev lists it',
        'row' => ['name' => 'GPT-6 Astra', 'reasoning' => true, 'images' => true, 'context' => 272_000, 'output' => 128_000, ...OPENAI_STANDARD_COSTS['gpt-6-astra']],
    ],
    'openai/gpt-6-sol' => [
        'kind' => 'add',
        'why' => 'upstream adds it until models.dev lists it',
        'row' => ['name' => 'GPT-6 Sol', 'reasoning' => true, 'images' => true, 'context' => 272_000, 'output' => 128_000, ...OPENAI_STANDARD_COSTS['gpt-6-sol']],
    ],
    'openai/gpt-6-luna' => [
        'kind' => 'add',
        'why' => 'upstream adds it until models.dev lists it',
        'row' => ['name' => 'GPT-6 Luna', 'reasoning' => true, 'images' => true, 'context' => 272_000, 'output' => 128_000, ...OPENAI_STANDARD_COSTS['gpt-6-luna']],
    ],
    'openai/gpt-5.6-sol' => [
        'kind' => 'add',
        'why' => 'upstream adds it until models.dev lists it',
        'row' => ['name' => 'GPT-5.6 Sol', 'reasoning' => true, 'images' => true, 'context' => 272_000, 'output' => 128_000, ...OPENAI_STANDARD_COSTS['gpt-5.6-sol']],
    ],
    'openai/gpt-5.6-terra' => [
        'kind' => 'add',
        'why' => 'upstream adds it until models.dev lists it',
        'row' => ['name' => 'GPT-5.6 Terra', 'reasoning' => true, 'images' => true, 'context' => 272_000, 'output' => 128_000, ...OPENAI_STANDARD_COSTS['gpt-5.6-terra']],
    ],
    'openai/gpt-5.6-luna' => [
        'kind' => 'add',
        'why' => 'upstream adds it until models.dev lists it',
        'row' => ['name' => 'GPT-5.6 Luna', 'reasoning' => true, 'images' => true, 'context' => 272_000, 'output' => 128_000, ...OPENAI_STANDARD_COSTS['gpt-5.6-luna']],
    ],
];



/**
 * Models the catalogue carries and pig does not offer.
 *
 * Upstream HEAD's `XAI_BUILTIN_EXCLUDED_MODEL_IDS`, applied as a straight filter the way upstream
 * applies it. It is knowledge models.dev does not carry — that these ids are listed and are not
 * usable — and it is the same kind of knowledge as the overrides above, one direction over.
 *
 * **Ported because the first real regeneration needed it.** `xai/grok-code-fast-1` had an
 * anchor-era `add` override here, on the grounds that models.dev did not list it. The override had
 * never fired, because at the anchor the catalogue *did* carry the model — with a 256,000 window,
 * a 10,000 output cap and reasoning on, which is what pig's transcribed row held. models.dev has
 * since dropped it, so the override fired for the first time and **replaced a good row with the
 * stale fallback beside it**: window 256000 → 32768, output 10000 → 8192, reasoning yes → no. An
 * override that has never been exercised is an override nobody has checked.
 *
 * Asking upstream what it thinks now settled which way to fix it: HEAD excludes that id outright,
 * along with `grok-3`, `grok-3-fast` and two preview ids. So the catalogue dropping it and
 * upstream excluding it agree, and re-adding it under any numbers would be offering a model that
 * cannot be talked to — which is the rule at the top of `Models` and the Groq 404 all over again.
 *
 * The reason upstream excludes each is not in its source and is not guessed at here. What is
 * checkable is that its list and models.dev disagree, and that following upstream is the safer
 * side of that disagreement.
 *
 * @var array<string, list<string>>
 */
const EXCLUDED = [
    // Upstream's `BEDROCK_INFERENCE_PROFILE_ONLY_MODEL_IDS`: served through an inference profile
    // (`us.`, `global.` …) only, so the bare id is not a model a request can name.
    'amazon-bedrock' => [
        'anthropic.claude-opus-5',
    ],
    'xai' => [
        'grok-3',
        'grok-3-fast',
        'grok-4.20-0309-non-reasoning',
        'grok-4.20-0309-reasoning',
        'grok-build-0.1',
        'grok-code-fast-1',
    ],
];

/**
 * Which API a Copilot model speaks.
 *
 * Upstream's rule, by id, because Copilot serves three shapes and the catalogue does not say
 * which. **Claude 4.x and 5.x go to Anthropic's Messages API** — upstream's `isCopilotClaude`,
 * `/^claude-(haiku|sonnet|opus|fable)-[45]([.\-]|$)/`, copied — so they get Anthropic's thinking
 * and caching, and no OpenAI `strict` on their tools. Then upstream's `needsResponsesApi`: "GPT,
 * Grok, OSWE, and MAI-Code models are only served through the Copilot /responses endpoint" — the
 * prefixes `gpt-`, `grok-`, `oswe` and `mai-`, with no exception for an older `gpt-4…` id. Anything
 * else (Gemini, Kimi) is on completions.
 */
function copilotApi(string $id): Api
{
    if (preg_match('/^claude-(haiku|sonnet|opus|fable)-[45]([.\-]|$)/', $id) === 1) {
        return Api::AnthropicMessages;
    }

    $needsResponsesApi = str_starts_with($id, 'gpt-')
        || str_starts_with($id, 'grok-')
        || str_starts_with($id, 'oswe')
        || str_starts_with($id, 'mai-');

    return $needsResponsesApi ? Api::OpenAiResponses : Api::OpenAiCompletions;
}

/** @return array<string, mixed> the models.dev document */
function catalogue(?string $file): array
{
    if ($file !== null) {
        if (!is_readable($file)) {
            fail("cannot read {$file}");
        }

        $text = (string) file_get_contents($file);
    } else {
        printf("fetching %s\n", MODELS_DEV);

        $text = Async::run(static function (): string {
            // `follow()` rather than `send()`: this is a file on somebody's CDN, not a streaming
            // API, so a 301 or 302 on the way to it is ordinary — which is the same reason
            // `ToolInstaller` uses it and the five providers do not.
            $response = (new HttpClient())->follow(new Request('GET', MODELS_DEV, ['accept' => 'application/json']));

            if (!$response->isSuccessful()) {
                fail(sprintf('models.dev answered %d', $response->status));
            }

            return $response->body->all();
        });
    }

    $data = json_decode($text, true);

    if (!is_array($data)) {
        fail('models.dev did not answer JSON: ' . json_last_error_msg());
    }

    return $data;
}

/**
 * One provider's rows, in the order the table keeps them.
 *
 * `tool_call !== true` is upstream's filter and it is not cosmetic: pig is an agent, so a model
 * that cannot be handed a tool cannot do the one thing it would be chosen for. A `deprecated` model
 * is left out for Copilot alone, which is where upstream's generator leaves it out among the
 * providers pig generates — Copilot marks a retired model rather than removing it.
 *
 * Per provider, what upstream's own processing of it does differently:
 *
 * - **google** (`processGoogleModels()`): `gemini-flash-latest` and `gemini-flash-lite-latest` read
 *   everything but their name from the model they alias, `gemini-3.5-flash` and
 *   `gemini-3.1-flash-lite` (when the catalogue lists it); and the row's `thinkingLevelMap` is
 *   `getGoogleThinkingLevelMap()` — the verified efforts, or Gemma 4's fixed map.
 * - **mistral**: the map is `getEffortThinkingLevelMap()` of the efforts — "Models with effort values
 *   use `reasoning_effort` with these levels. Reasoning models without them (Magistral) use
 *   `prompt_mode`" — a missing cache-read price is a tenth of the input price, and no tiers.
 * - **zai** (`processZaiModels()`): the rows are `zai-coding-plan`'s (`SOURCE`), priced from `zai`'s
 *   entry when it has one; the map is the efforts', with `off: "none"` for GLM-5.2.
 * - **google-vertex** (the end of `processGoogleModels()`): "The google-vertex models.dev catalog
 *   also includes Claude, OpenAI, and other MaaS models that do not use the @google/genai Gemini
 *   streaming path" — so `gemini-` ids only, and not `gemini-3.1-flash-lite-preview`; the two
 *   `-latest` aliases read their aliased model as on `google`; the map is
 *   `getGoogleThinkingLevelMap()`; no tiers, no cache-write price, and Gemini 2.5 Flash's cache read
 *   is 0.03 — "models.dev reports Vertex cache_read/cache_write values for Gemini 2.5 Flash that do
 *   not match the official Gemini API standard pricing table. pi only accounts
 *   cachedContentTokenCount as cacheRead."
 * - **amazon-bedrock**: not AI21's Jamba ("These models doesn't support tool use in streaming
 *   mode") or Mistral 7B Instruct v0 ("These models doesn't support system messages"), nor
 *   `EXCLUDED`'s inference-profile-only id; and `strictMode` (upstream's
 *   `compat: {supportsStrictMode: true}`) where models.dev says `structured_output`. No map: upstream
 *   records the reasoning options, but `supportsDirectReasoningEffort()` is false for
 *   `bedrock-converse-stream`, and the map `Models` gives a Bedrock row is the ids'.
 *
 * @param array<string, mixed> $catalogue
 * @return array<string, array<string, mixed>>
 */
function rowsFor(array $catalogue, string $provider): array
{
    $source = SOURCE[$provider] ?? $provider;
    $models = $catalogue[$source]['models'] ?? null;

    if (!is_array($models)) {
        // Named, not skipped: a provider that has vanished from models.dev is either a rename
        // this script has to learn or an endpoint that is gone, and both need a person.
        printf("  ! %s is not in this catalogue at all\n", $source);

        return [];
    }

    $rows = [];

    foreach ($models as $id => $model) {
        if (!is_string($id) || !is_array($model)) {
            continue;
        }

        if (($model['tool_call'] ?? null) !== true) {
            continue;
        }

        // Copilot marks a retired model rather than removing it.
        if ($provider === 'github-copilot' && ($model['status'] ?? null) === 'deprecated') {
            continue;
        }

        if ($provider === 'google-vertex' && (!str_starts_with($id, 'gemini-') || $id === 'gemini-3.1-flash-lite-preview')) {
            continue;
        }

        if ($provider === 'amazon-bedrock' && (str_starts_with($id, 'ai21.jamba') || str_starts_with($id, 'mistral.mistral-7b-instruct-v0'))) {
            continue;
        }

        if (in_array($id, EXCLUDED[$provider] ?? [], true)) {
            printf("  · %s/%s is listed and not offered — see EXCLUDED\n", $provider, $id);

            continue;
        }

        // `gemini-flash-latest` is `gemini-3.5-flash` under another name, and models.dev's own
        // entry for the alias lags behind — upstream reads the aliased model instead.
        $from = $model;

        if (($provider === 'google' || $provider === 'google-vertex') && ($id === 'gemini-flash-latest' || $id === 'gemini-flash-lite-latest')) {
            $aliased = $models[$id === 'gemini-flash-latest' ? 'gemini-3.5-flash' : 'gemini-3.1-flash-lite'] ?? null;
            $from = is_array($aliased) ? $aliased : $model;
        }

        $input = $from['modalities']['input'] ?? [];
        $cost = $provider === 'zai' && is_array($catalogue['zai']['models'][$id]['cost'] ?? null)
            ? $catalogue['zai']['models'][$id]['cost']
            : ($from['cost'] ?? null);
        $tiers = $provider === 'mistral' || $provider === 'google-vertex' ? [] : tiers($cost);
        $reasoningOptions = is_array($from['reasoning_options'] ?? null) ? $from['reasoning_options'] : [];
        // Upstream's `recordModelsDevReasoningOptions(provider, id, m)`, read back by
        // `applyModelsDevReasoningOptionMetadata()`. That reader needs the model's api and compat
        // (`supportsDirectReasoningEffort()`), which pig works out in `Models::table()` and not
        // here — so what the row carries is the options' effort map, the part that depends on the
        // catalogue alone, and `Models` decides whether it applies. See `effortLevelMap` there.
        $effortLevelMap = in_array($provider, REASONING_OPTION_PROVIDERS, true) && is_array($model['reasoning_options'] ?? null)
            ? getEffortThinkingLevelMap($model['reasoning_options'])
            : null;
        $thinkingLevelMap = match ($provider) {
            'google', 'google-vertex' => getGoogleThinkingLevelMap($id, $reasoningOptions),
            'mistral' => getEffortThinkingLevelMap($reasoningOptions),
            'zai' => zaiThinkingLevelMap($id, $reasoningOptions),
            default => null,
        };
        $in = (float) ($cost['input'] ?? 0);

        $rows[$id] = [
            'name' => is_string($model['name'] ?? null) && $model['name'] !== '' ? $model['name'] : $id,
            'reasoning' => ($from['reasoning'] ?? null) === true,
            'images' => is_array($input) && in_array('image', $input, true),
            'context' => (int) ($from['limit']['context'] ?? 0),
            'output' => (int) ($from['limit']['output'] ?? 0),
            'input' => $in,
            'out' => (float) ($cost['output'] ?? 0),
            // Mistral: `m.cost?.cache_read ?? (m.cost?.input ? roundCost(m.cost.input * 0.1) : 0)`.
            'cacheRead' => match (true) {
                $provider === 'mistral' && !is_numeric($cost['cache_read'] ?? null) => $in != 0.0 ? roundCost($in * 0.1) : 0.0,
                $provider === 'google-vertex' && $id === 'gemini-2.5-flash' => 0.03,
                default => (float) ($cost['cache_read'] ?? 0),
            },
            'cacheWrite' => $provider === 'google-vertex' ? 0.0 : (float) ($cost['cache_write'] ?? 0),
            ...($thinkingLevelMap === null ? [] : ['thinkingLevelMap' => $thinkingLevelMap]),
            ...($tiers === [] ? [] : ['tiers' => $tiers]),
            ...($effortLevelMap === null ? [] : ['effortLevelMap' => $effortLevelMap]),
            ...($provider === 'amazon-bedrock' && ($model['structured_output'] ?? null) === true ? ['strictMode' => true] : []),
        ];
    }

    ksort($rows);

    return $rows;
}

/**
 * Upstream's `isGemma4Model()` and `getGoogleThinkingLevelMap()`: the verified efforts' map when
 * models.dev lists any, else Gemma 4's — which takes only Google's `MINIMAL` and `HIGH` and cannot
 * be switched off — else none.
 *
 * @param array<mixed> $reasoningOptions
 * @return array<string, string|null>|null
 */
function getGoogleThinkingLevelMap(string $modelId, array $reasoningOptions): ?array
{
    $effortMap = getEffortThinkingLevelMap($reasoningOptions);

    if ($effortMap !== null) {
        return $effortMap;
    }

    if (preg_match('/gemma-?4/', strtolower($modelId)) === 1) {
        return ['off' => null, 'minimal' => 'MINIMAL', 'low' => null, 'medium' => null, 'high' => 'HIGH'];
    }

    return null;
}

/**
 * `processZaiModels()`'s map: the verified efforts', and for GLM-5.2 `off: "none"` on it.
 *
 * @param array<mixed> $reasoningOptions
 * @return array<string, string|null>|null
 */
function zaiThinkingLevelMap(string $modelId, array $reasoningOptions): ?array
{
    $map = getEffortThinkingLevelMap($reasoningOptions);

    if ($map !== null && in_array($modelId, ZAI_GLM52_IDS, true)) {
        $map['off'] = 'none';
    }

    return $map;
}

/**
 * Upstream's `getModelsDevCost()` tiers: each `cost.tiers` entry whose `tier` is `{type: "context",
 * size}` becomes `[size, in, out, cache read, cache write]`, a rate it does not list keeping the base
 * price ("Rates a tier does not list keep the base price"); anything else is skipped.
 *
 * @return list<array{0: int, 1: float, 2: float, 3: float, 4: float}>
 */
function tiers(mixed $cost): array
{
    if (!is_array($cost) || !is_array($cost['tiers'] ?? null)) {
        return [];
    }

    $base = [
        (float) ($cost['input'] ?? 0),
        (float) ($cost['output'] ?? 0),
        (float) ($cost['cache_read'] ?? 0),
        (float) ($cost['cache_write'] ?? 0),
    ];
    $tiers = [];

    foreach ($cost['tiers'] as $tier) {
        $context = is_array($tier) ? ($tier['tier'] ?? null) : null;

        if (!is_array($context) || ($context['type'] ?? null) !== 'context' || !is_numeric($context['size'] ?? null)) {
            continue;
        }

        $tiers[] = [
            (int) $context['size'],
            is_numeric($tier['input'] ?? null) ? (float) $tier['input'] : $base[0],
            is_numeric($tier['output'] ?? null) ? (float) $tier['output'] : $base[1],
            is_numeric($tier['cache_read'] ?? null) ? (float) $tier['cache_read'] : $base[2],
            is_numeric($tier['cache_write'] ?? null) ? (float) $tier['cache_write'] : $base[3],
        ];
    }

    return $tiers;
}

/**
 * Upstream's `getEffortThinkingLevelMap()` (`scripts/models-dev-reasoning-options.ts`), literally:
 * "Converts models.dev verified effort values into Pi's selectable thinking levels. Values without a
 * Pi equivalent (`default` and JSON `null`) are intentionally omitted."
 *
 * Null (upstream's undefined) when no `effort` option lists a value, or none of the values listed
 * is a pi level or `none`. Otherwise every key, in upstream's order: `off` is `"none"` when the
 * model takes `none` and null when it does not, and each level is its own name or null.
 *
 * @param array<mixed> $options models.dev's `reasoning_options`
 * @return array<string, string|null>|null
 */
function getEffortThinkingLevelMap(array $options): ?array
{
    $effortValues = [];

    foreach ($options as $option) {
        if (is_array($option) && ($option['type'] ?? null) === 'effort' && is_array($option['values'] ?? null)) {
            $effortValues = [...$effortValues, ...array_values($option['values'])];
        }
    }

    if ($effortValues === []) {
        return null;
    }

    // `new Set(effortValues)` and `.has()`: strict, so a JSON null in the list is no level.
    $supported = static fn (string $value): bool => in_array($value, $effortValues, true);
    $anyLevel = false;

    foreach (EFFORT_THINKING_LEVELS as $level) {
        $anyLevel = $anyLevel || $supported($level);
    }

    if (!$anyLevel && !$supported('none')) {
        return null;
    }

    $map = ['off' => $supported('none') ? 'none' : null];

    foreach (EFFORT_THINKING_LEVELS as $level) {
        $map[$level] = $supported($level) ? $level : null;
    }

    return $map;
}

/** Upstream's `roundCost()`: `Number(value.toFixed(6))`. */
function roundCost(float $value): float
{
    return round($value, 6);
}

/**
 * Upstream's `withOpenAiLongContextPricing(cost)`, on a row's price keys: the base kept, and one tier
 * above `OPENAI_LONG_CONTEXT_INPUT_THRESHOLD` at twice the input and cache rates and one and a half
 * times the output — replacing whatever tiers the row had, as upstream's `tiers: [...]` does.
 *
 * @param array<string, mixed> $row
 * @return array<string, mixed>
 */
function withOpenAiLongContextPricing(array $row): array
{
    $row['tiers'] = [[
        OPENAI_LONG_CONTEXT_INPUT_THRESHOLD,
        roundCost((float) $row['input'] * 2),
        roundCost((float) $row['out'] * 1.5),
        roundCost((float) $row['cacheRead'] * 2),
        roundCost((float) $row['cacheWrite'] * 2),
    ]];

    return $row;
}

/**
 * The `openai` lines of upstream's "Temporary overrides until upstream model metadata is corrected"
 * loop in `generateModels()`, in its order, after the catalogue and the hand-written rows:
 *
 * - `OPENAI_SHORT_CONTEXT_CAPPED_MODEL_IDS` get `contextWindow = OPENAI_LONG_CONTEXT_INPUT_THRESHOLD`
 *   and `maxTokens = 128000` — the 272k cap, which is a window and so where compaction fires;
 * - `OPENAI_LONG_CONTEXT_PRICING_MODEL_IDS` get `withOpenAiLongContextPricing(OPENAI_STANDARD_COSTS[id]
 *   ?? cost)`;
 * - `gpt-5-pro` gets `maxTokens = 128000`: "models.dev reports gpt-5-pro output as 272000 (a
 *   duplicate of the input sub-limit); the actual max output is 128000."
 *
 * Applied every run, silently, as upstream applies them — they are rules, not corrections with a
 * value that can go stale, so `OVERRIDES`' "changes nothing any more" report does not fit them.
 * The loop's other lines are for providers pig does not generate, or are `OVERRIDES` already
 * (Copilot's extended windows).
 *
 * @param array<string, array<string, mixed>> $rows
 * @return array<string, array<string, mixed>>
 */
function openAiTemporaryOverrides(array $rows, string $provider): array
{
    if ($provider !== 'openai') {
        return $rows;
    }

    foreach ($rows as $id => $row) {
        if (in_array($id, OPENAI_SHORT_CONTEXT_CAPPED_MODEL_IDS, true)) {
            $row['context'] = OPENAI_LONG_CONTEXT_INPUT_THRESHOLD;
            $row['output'] = 128_000;
        }

        if (in_array($id, OPENAI_LONG_CONTEXT_PRICING_MODEL_IDS, true)) {
            $row = withOpenAiLongContextPricing([...$row, ...(OPENAI_STANDARD_COSTS[$id] ?? [])]);
        }

        if ($id === 'gpt-5-pro') {
            $row['output'] = 128_000;
        }

        $rows[$id] = $row;
    }

    return $rows;
}

/**
 * The `github-copilot` lines of upstream's "Temporary overrides until upstream model metadata is
 * corrected" loop: every row in `GITHUB_COPILOT_EXTENDED_CONTEXT_MODELS` gets `contextWindow =
 * 1000000`. A rule, applied every run and silently, as `openAiTemporaryOverrides()` is — after the
 * hand-added rows, as upstream's loop runs after `missingCopilotModels`.
 *
 * @param array<string, array<string, mixed>> $rows
 * @return array<string, array<string, mixed>>
 */
function copilotTemporaryOverrides(array $rows): array
{
    foreach ($rows as $id => $row) {
        if (in_array($id, GITHUB_COPILOT_EXTENDED_CONTEXT_MODELS, true)) {
            $rows[$id]['context'] = 1_000_000;
        }
    }

    return $rows;
}

/**
 * Upstream's defaults for a limit the catalogue left out.
 *
 * **Complained about rather than applied quietly.** Upstream writes `m.limit?.context || 4096`,
 * which turns a missing window into a number small enough to make every conversation look nearly
 * full, and a missing output cap into one that truncates every answer. The default is kept so a
 * row is still usable, and the complaint is what gets somebody to go and look.
 *
 * @param array<string, array<string, mixed>> $rows
 * @return array<string, array<string, mixed>>
 */
function fillLimits(array $rows, string $provider, int $window, int $output): array
{
    foreach ($rows as $id => $row) {
        if ($row['context'] <= 0) {
            printf("  ! %s/%s has no context window in the catalogue — using %d\n", $provider, $id, $window);
            $rows[$id]['context'] = $window;
        }

        if ($row['output'] <= 0) {
            printf("  ! %s/%s has no output limit in the catalogue — using %d\n", $provider, $id, $output);
            $rows[$id]['output'] = $output;
        }
    }

    return $rows;
}

/**
 * @param array<string, array<string, mixed>> $rows
 * @return array<string, array<string, mixed>>
 */
function applyOverrides(array $rows, string $provider): array
{
    foreach (OVERRIDES as $key => $override) {
        [$who, $id] = explode('/', $key, 2);

        if ($who !== $provider) {
            continue;
        }

        if (isset($rows[$id])) {
            printf("  · the catalogue now carries %s, so the hand-written one is dropped\n", $key);

            continue;
        }

        $rows[$id] = $override['row'];
        printf("  · %s added by hand: %s\n", $key, $override['why']);
    }

    ksort($rows);

    return $rows;
}

/** A number the table writes with underscores, as every row in it already does. */
function grouped(int $value): string
{
    return number_format($value, 0, '.', '_');
}

/** A price, always with a decimal point so a column of them reads as money. */
function money(float $value): string
{
    $text = rtrim(rtrim(sprintf('%.10F', $value), '0'), '.');

    return $text === '' || !str_contains($text, '.') ? ($text === '' ? '0.0' : $text . '.0') : $text;
}

/**
 * The rows of one table, as the PHP text that goes between the markers.
 *
 * Three shapes, because the tables have three shapes and this writes what is there rather than
 * widening them: Anthropic has no images column (everything it sells takes images, and
 * `assertImages()` is what keeps that true), Copilot has an api column before the others, and the
 * other nine are the full nine. Copilot's rows carry models.dev's list prices, as upstream's
 * generator writes them (`cost: getModelsDevCost(m.cost)`); they used to carry none, on the grounds
 * that a subscription is not metered per token, which made `/session` say $0.00 where pi says what
 * the same tokens are worth.
 *
 * @param array<string, array<string, mixed>> $rows
 */
function render(array $rows, string $constant): string
{
    $lines = [];

    foreach ($rows as $id => $row) {
        $cells = [var_export($row['name'], true)];

        if ($constant === 'COPILOT_MODELS') {
            $cells[] = 'Api::' . copilotApi($id)->name;
        }

        $cells[] = grouped((int) $row['context']);
        $cells[] = grouped((int) $row['output']);
        $cells[] = $row['reasoning'] ? 'true' : 'false';

        if ($constant !== 'ANTHROPIC_MODELS') {
            $cells[] = $row['images'] ? 'true' : 'false';
        }

        foreach (['input', 'out', 'cacheRead', 'cacheWrite'] as $field) {
            $cells[] = money((float) $row[$field]);
        }

        // The row's own level map — Google's, Mistral's and z.ai's from the catalogue, an
        // override's measurement, a hand-added row's — under its own key, only where there is one.
        if (isset($row['thinkingLevelMap'])) {
            $cells[] = "'thinkingLevelMap' => " . levelMap($row['thinkingLevelMap']);
        }

        // Tiers under their own key, in any table.
        if (($row['tiers'] ?? []) !== []) {
            $cells[] = "'tiers' => [" . implode(', ', array_map(
                static fn (array $tier): string => sprintf('[%s, %s, %s, %s, %s]', grouped((int) $tier[0]), money((float) $tier[1]), money((float) $tier[2]), money((float) $tier[3]), money((float) $tier[4])),
                $row['tiers'],
            )) . ']';
        }

        // models.dev's verified efforts, under their own key in any table — see `rowsFor()`.
        if (isset($row['effortLevelMap'])) {
            $cells[] = "'effortLevelMap' => " . levelMap($row['effortLevelMap']);
        }

        // Bedrock's `compat: {supportsStrictMode: true}`.
        if (($row['strictMode'] ?? false) === true) {
            $cells[] = "'strictMode' => true";
        }

        $lines[] = sprintf("        %s => [%s],", var_export($id, true), implode(', ', $cells));
    }

    return implode("\n", $lines);
}

/** `['off' => null, 'minimal' => null]` as the generated file writes it. */
function levelMap(array $map): string
{
    $cells = [];

    foreach ($map as $level => $sent) {
        $cells[] = sprintf('%s => %s', var_export($level, true), $sent === null ? 'null' : var_export($sent, true));
    }

    return '[' . implode(', ', $cells) . ']';
}

/**
 * Anthropic's table cannot say "no images", so the assumption behind it is checked.
 *
 * @param array<string, array<string, mixed>> $rows
 */
function assertImages(array $rows): void
{
    foreach ($rows as $id => $row) {
        if ($row['images'] !== true) {
            printf("  ! anthropic/%s takes no images, which ANTHROPIC_MODELS has no column for\n", $id);
        }
    }
}

/** Replace what lies between one table's markers, and nothing else in the file. */
function splice(string $source, string $constant, string $rows): string
{
    $pattern = '/(private const array ' . preg_quote($constant, '/')
        . " = \\[\n        \\/\\/ >>> generated[^\n]*\n)(.*?)(\n        \\/\\/ <<< generated\n)/s";

    $replaced = preg_replace($pattern, '${1}' . str_replace('$', '\\$', $rows) . '${3}', $source, 1, $count);

    if ($replaced === null || $count !== 1) {
        fail("could not find the generated block for {$constant} — are its markers still there?");
    }

    return $replaced;
}

function fail(string $message): never
{
    fwrite(STDERR, "generate-models: {$message}\n");

    exit(1);
}

// ---- what changed --------------------------------------------------------------------------

/**
 * The table as it stands, before anything is written, keyed the way the file keys it.
 *
 * @return array<string, Model>
 */
function currently(): array
{
    $now = [];

    foreach (Models::all() as $model) {
        $now[$model->provider . '/' . $model->id] = $model;
    }

    return $now;
}

/**
 * @param array<string, Model> $before
 * @param array<string, Model> $after
 */
function report(array $before, array $after): void
{
    $gone = array_diff_key($before, $after);
    $added = array_diff_key($after, $before);
    $moved = [];

    foreach (array_intersect_key($after, $before) as $key => $model) {
        $was = $before[$key];
        $fields = [];

        if ($was->name !== $model->name) {
            $fields[] = sprintf('name %s → %s', $was->name, $model->name);
        }

        if ($was->contextWindow !== $model->contextWindow) {
            $fields[] = sprintf('window %d → %d', $was->contextWindow, $model->contextWindow);
        }

        if ($was->maxTokens !== $model->maxTokens) {
            $fields[] = sprintf('output %d → %d', $was->maxTokens, $model->maxTokens);
        }

        if ($was->reasoning !== $model->reasoning) {
            $fields[] = sprintf('reasoning %s → %s', $was->reasoning ? 'yes' : 'no', $model->reasoning ? 'yes' : 'no');
        }

        if ($was->acceptsImages() !== $model->acceptsImages()) {
            $fields[] = sprintf('images %s → %s', $was->acceptsImages() ? 'yes' : 'no', $model->acceptsImages() ? 'yes' : 'no');
        }

        if ($was->thinkingLevelMap !== $model->thinkingLevelMap) {
            $fields[] = sprintf('levels %s → %s', json_encode($was->thinkingLevelMap), json_encode($model->thinkingLevelMap));
        }

        foreach (['input', 'output', 'cacheRead', 'cacheWrite'] as $field) {
            if (abs($was->pricing->{$field} - $model->pricing->{$field}) > 1e-9) {
                $fields[] = sprintf('%s $%s → $%s', $field, money($was->pricing->{$field}), money($model->pricing->{$field}));
            }
        }

        if (json_encode($was->pricing->tiers) !== json_encode($model->pricing->tiers)) {
            $fields[] = sprintf('tiers %s → %s', json_encode($was->pricing->tiers), json_encode($model->pricing->tiers));
        }

        if ($fields !== []) {
            $moved[$key] = $fields;
        }
    }

    printf("\n%d added, %d gone, %d changed\n", count($added), count($gone), count($moved));

    foreach (array_keys($added) as $key) {
        printf("  + %s\n", $key);
    }

    foreach (array_keys($gone) as $key) {
        printf("  - %s\n", $key);
    }

    foreach ($moved as $key => $fields) {
        printf("  ~ %s: %s\n", $key, implode('; ', $fields));
    }
}

// ---- the run -------------------------------------------------------------------------------

$from = null;
$dryRun = false;

for ($i = 1; $i < $argc; $i++) {
    if ($argv[$i] === '--dry-run') {
        $dryRun = true;
    } elseif ($argv[$i] === '--from' && isset($argv[$i + 1])) {
        $from = $argv[++$i];
    } else {
        fail("unknown argument {$argv[$i]} — usage: generate-models.php [--from <file>] [--dry-run]");
    }
}

$before = currently();
$catalogue = catalogue($from);
$source = (string) file_get_contents(TABLE);
$counts = [];

foreach (DIRECT as $provider => [$constant]) {
    printf("%s\n", $provider);
    $rows = openAiTemporaryOverrides(applyOverrides(fillLimits(rowsFor($catalogue, $provider), $provider, 4_096, 4_096), $provider), $provider);

    if ($provider === 'anthropic') {
        assertImages($rows);
    }

    if ($rows === []) {
        // An empty table would take every one of that provider's models out of pig in silence.
        printf("  ! nothing to write for %s, so its table is left as it is\n", $provider);

        continue;
    }

    $rendered = render($rows, $constant);
    $source = splice($source, $constant, $rendered);
    $counts[$provider] = count($rows);

    if ($dryRun) {
        printf("%s\n", $rendered);
    }
}

// Copilot's defaults are its own — upstream's 128000/8192 rather than 4096, because its
// catalogue omits the limits far more often and 4096 there would truncate every answer.
printf("github-copilot\n");
$copilot = copilotTemporaryOverrides(applyOverrides(fillLimits(rowsFor($catalogue, 'github-copilot'), 'github-copilot', 128_000, 8_192), 'github-copilot'));

if ($copilot !== []) {
    $rendered = render($copilot, 'COPILOT_MODELS');
    $source = splice($source, 'COPILOT_MODELS', $rendered);
    $counts['github-copilot'] = count($copilot);

    if ($dryRun) {
        printf("%s\n", $rendered);
    }
} else {
    printf("  ! nothing to write for github-copilot, so its table is left as it is\n");
}

printf("\n");

foreach ($counts as $provider => $count) {
    printf("%-16s %d models\n", $provider, $count);
}

if ($dryRun) {
    printf("\n--dry-run: nothing written\n");

    exit(0);
}

if (file_put_contents(TABLE, $source) === false) {
    fail('could not write ' . TABLE);
}

// Re-read the table through a fresh process: this one has the old constants loaded, and PHP
// cannot be told to forget a class it has already resolved.
$reload = sprintf(
    '%s -r %s',
    escapeshellarg(PHP_BINARY),
    escapeshellarg(
        'require ' . var_export(__DIR__ . '/../vendor/autoload.php', true) . ';'
        . 'foreach (Pig\Ai\Models::all() as $m) { echo $m->provider, "/", $m->id, "\t", $m->name, "\t",'
        . '$m->contextWindow, "\t", $m->maxTokens, "\t", $m->reasoning ? 1 : 0, "\t",'
        . '$m->acceptsImages() ? 1 : 0, "\t", $m->pricing->input, "\t", $m->pricing->output, "\t",'
        . '$m->pricing->cacheRead, "\t", $m->pricing->cacheWrite, "\t", json_encode($m->thinkingLevelMap), "\t",'
        . 'json_encode(array_map(static fn ($t) => [$t->inputTokensAbove, $t->input, $t->output, $t->cacheRead, $t->cacheWrite], $m->pricing->tiers)), "\n"; }',
    ),
);

exec($reload, $output, $status);

if ($status !== 0) {
    fail('the rewritten table does not load — ' . TABLE . ' is written and needs looking at');
}

$after = [];

foreach ($output as $line) {
    [$key, $name, $window, $max, $reasoning, $images, $in, $out, $read, $write, $levels, $tiers] = explode("\t", $line);
    [$provider, $id] = explode('/', $key, 2);
    $after[$key] = new Model(
        $id,
        $name,
        Api::AnthropicMessages,
        $provider,
        '',
        (int) $window,
        (int) $max,
        $reasoning === '1',
        $images === '1' ? ['text', 'image'] : ['text'],
        new Pig\Ai\Pricing((float) $in, (float) $out, (float) $read, (float) $write, array_map(
            static fn (array $tier): Pig\Ai\PricingTier => new Pig\Ai\PricingTier((int) $tier[0], (float) $tier[1], (float) $tier[2], (float) $tier[3], (float) $tier[4]),
            (array) json_decode($tiers, true),
        )),
        // `[]` encodes as a list and decodes as one, which is the same empty map.
        thinkingLevelMap: (array) json_decode($levels, true),
    );
}

report($before, $after);

printf("\nwritten: %s\n", TABLE);
